### ISSUE TITLE
No module named 'DOTA_devkit'

### ISSUE THREAD

**Issue by fanhaiting** [SunYM2020/DetFusion#13]

**Comment by Sunshinelysy** [comment]
解决了吗？我也遇到了这个问题，不知道该怎么办
ModuleNotFoundError: No module named 'DOTA_devkit'

**Comment by SunYM2020** [comment]
Please refer to [link](https://github.com/SunYM2020/UA-CMDet/issues/29#issuecomment-2080920085).

**Comment by SunYM2020** [comment]
Put the folder “DOTA_devkit” into the “DetFusion/”.
