### ISSUE TITLE
How did the 'data/LLVIP/train.txt' come from?  

### ISSUE THREAD

**Issue by fanhaiting** [SunYM2020/DetFusion#14]
Hope you can provide some explanation for the dataset，Thanks!

**Comment by SunYM2020** [comment]
The LLVIP refer to [LLVIP](https://github.com/bupt-ai-cz/LLVIP).

'train.txt' refer to [link](https://github.com/SunYM2020/DetFusion/issues/4#issuecomment-1373491870)
