### ISSUE TITLE
你好，请问你的dataset是怎么处理的呢

### ISSUE THREAD

**Issue by zlw1113** [SunYM2020/DetFusion#4]
![image](https://user-images.githubusercontent.com/44747412/210926722-66110b0b-ae7d-4741-b462-2f77040417f8.png)
请问这个train.txt包含了什么呢，似乎和LLVIP的默认格式不太一致，感谢！

**Comment by SunYM2020** [comment]
> 
train.txt contains the index number of the pictures in the training set.
![image](https://user-images.githubusercontent.com/108861263/211002648-5644c515-17ca-49ee-a0f4-d7c7f5969294.png)

**Comment by zlw1113** [comment]
感谢！
