### ISSUE TITLE
关于环境请教一些问题

### ISSUE THREAD

**Issue by BlackLotus12138** [SunYM2020/DetFusion#7]
请问为什么要安装mmcv<=0.2.14啊？
网络框架可以适配高版本的mmdet吗？
（我是刚刚接触这方面，还望大佬不吝赐教）

**Comment by BlackLotus12138** [comment]
如果可以的话，大佬可以出一篇复现教程吗，万分感谢！

**Comment by SunYM2020** [comment]
The repository is based on mmdet with version number '0.6.0+0b9addf' which requires “mmcv<=0.2.14”. I'm sorry I haven't tested it on a higher version.

**Comment by BlackLotus12138** [comment]
感谢！
