### ISSUE TITLE
  File "/home/ywc/temp/DetFusion/mmdet/models/bbox_heads/fusion_head_bbox.py", line 72, in forward     enc_fusion = enc_fusion + enc_fusion * up_att_w  RuntimeError: The size of tensor a (640) must match the size of tensor b (608) at non-singleton dimension 3

### ISSUE THREAD

**Issue by yanwencheng000** [SunYM2020/DetFusion#8]
Dimension mismatch

**Comment by yanwencheng000** [comment]
File "/home/ywc/temp/DetFusion/test.py", line 31, in <module>
    save_fusion_result('./configs/DetFusion.py', './work_dirs/DetFusion/model.pth', img_dir='./evaluateimgs/')
  File "/home/ywc/temp/DetFusion/test.py", line 26, in save_fusion_result
    image_fusion = inference_detector(model, img_path_r, img_path_i)
  File "/home/ywc/temp/DetFusion/mmdet/apis/inference.py", line 60, in inference_detector
    return _inference_single(model, imgs_r, imgs_i, img_transform, device)
  File "/home/ywc/temp/DetFusion/mmdet/apis/inference.py", line 120, in _inference_single
    result_r, result_i, image_fusion = model(return_loss=False, rescale=True, **data)
  File "/home/ywc/miniconda3/envs/detfusion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ywc/temp/DetFusion/mmdet/models/detectors/base.py", line 116, in forward
    return self.forward_test(img_r, img_i, img_meta, source_img_r, source_img_i, **kwargs)
  File "/home/ywc/temp/DetFusion/mmdet/models/detectors/base.py", line 107, in forward_test
    return self.simple_test(imgs_r[0], imgs_i[0], img_metas[0], source_img_r[0], source_img_i[0], **kwargs)
  File "/home/ywc/temp/DetFusion/mmdet/models/detectors/detfusion.py", line 556, in simple_test
    im_fusion = self.fusion_head(source_img_r/255.0, source_img_i/255.0, att_rgb, att_tir)
  File "/home/ywc/miniconda3/envs/detfusion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ywc/temp/DetFusion/mmdet/models/bbox_heads/fusion_head_bbox.py", line 72, in forward
    enc_fusion = enc_fusion + enc_fusion * up_att_w 
RuntimeError: The size of tensor a (640) must match the size of tensor b (608) at non-singleton dimension 3

**Comment by BlackLotus12138** [comment]
你也在复现这篇论文吗，如果成功的话能不能发我一份，谢谢！

**Comment by SunYM2020** [comment]
It may be that the dimensions of "up_att_w" and "enc_fusion" do not match, and you should check your input data to debug it.

> File "/home/ywc/temp/DetFusion/test.py", line 31, in save_fusion_result('./configs/DetFusion.py', './work_dirs/DetFusion/model.pth', img_dir='./evaluateimgs/') File "/home/ywc/temp/DetFusion/test.py", line 26, in save_fusion_result image_fusion = inference_detector(model, img_path_r, img_path_i) File "/home/ywc/temp/DetFusion/mmdet/apis/inference.py", line 60, in inference_detector return _inference_single(model, imgs_r, imgs_i, img_transform, device) File "/home/ywc/temp/DetFusion/mmdet/apis/inference.py", line 120, in _inference_single result_r, result_i, image_fusion = model(return_loss=False, rescale=True, **data) File "/home/ywc/miniconda3/envs/detfusion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/ywc/temp/DetFusion/mmdet/models/detectors/base.py", line 116, in forward return self.forward_test(img_r, img_i, img_meta, source_img_r, source_img_i, **kwargs) File "/home/ywc/temp/DetFusion/mmdet/models/detectors/base.py", line 107, in forward_test return self.simple_test(imgs_r[0], imgs_i[0], img_metas[0], source_img_r[0], source_img_i[0], **kwargs) File "/home/ywc/temp/DetFusion/mmdet/models/detectors/detfusion.py", line 556, in simple_test im_fusion = self.fusion_head(source_img_r/255.0, source_img_i/255.0, att_rgb, att_tir) File "/home/ywc/miniconda3/envs/detfusion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/ywc/temp/DetFusion/mmdet/models/bbox_heads/fusion_head_bbox.py", line 72, in forward enc_fusion = enc_fusion + enc_fusion * up_att_w RuntimeError: The size of tensor a (640) must match the size of tensor b (608) at non-singleton dimension 3

It may be that the dimensions of "up_att_w" and "enc_fusion" do not match, and you should check your input data to debug it.

**Comment by 2252033991** [comment]
> 你也在复现这篇论文吗，如果成功的话能不能发我一份，谢谢！

请问你成功了吗

**Comment by 2252033991** [comment]
> File "/home/ywc/temp/DetFusion/test.py", line 31, in save_fusion_result('./configs/DetFusion.py', './work_dirs/DetFusion/model.pth', img_dir='./evaluateimgs/') File "/home/ywc/temp/DetFusion/test.py", line 26, in save_fusion_result image_fusion = inference_detector(model, img_path_r, img_path_i) File "/home/ywc/temp/DetFusion/mmdet/apis/inference.py", line 60, in inference_detector return _inference_single(model, imgs_r, imgs_i, img_transform, device) File "/home/ywc/temp/DetFusion/mmdet/apis/inference.py", line 120, in _inference_single result_r, result_i, image_fusion = model(return_loss=False, rescale=True, **data) File "/home/ywc/miniconda3/envs/detfusion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/ywc/temp/DetFusion/mmdet/models/detectors/base.py", line 116, in forward return self.forward_test(img_r, img_i, img_meta, source_img_r, source_img_i, **kwargs) File "/home/ywc/temp/DetFusion/mmdet/models/detectors/base.py", line 107, in forward_test return self.simple_test(imgs_r[0], imgs_i[0], img_metas[0], source_img_r[0], source_img_i[0], **kwargs) File "/home/ywc/temp/DetFusion/mmdet/models/detectors/detfusion.py", line 556, in simple_test im_fusion = self.fusion_head(source_img_r/255.0, source_img_i/255.0, att_rgb, att_tir) File "/home/ywc/miniconda3/envs/detfusion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/ywc/temp/DetFusion/mmdet/models/bbox_heads/fusion_head_bbox.py", line 72, in forward enc_fusion = enc_fusion + enc_fusion * up_att_w RuntimeError: The size of tensor a (640) must match the size of tensor b (608) at non-singleton dimension 3

Pls how to solve this problem, I am also experiencing such a problem

**Comment by 2252033991** [comment]
> File "/home/ywc/temp/DetFusion/test.py", line 31, in save_fusion_result('./configs/DetFusion.py', './work_dirs/DetFusion/model.pth', img_dir='./evaluateimgs/') File "/home/ywc/temp/DetFusion/test.py", line 26, in save_fusion_result image_fusion = inference_detector(model, img_path_r, img_path_i) File "/home/ywc/temp/DetFusion/mmdet/apis/inference.py", line 60, in inference_detector return _inference_single(model, imgs_r, imgs_i, img_transform, device) File "/home/ywc/temp/DetFusion/mmdet/apis/inference.py", line 120, in _inference_single result_r, result_i, image_fusion = model(return_loss=False, rescale=True, **data) File "/home/ywc/miniconda3/envs/detfusion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/ywc/temp/DetFusion/mmdet/models/detectors/base.py", line 116, in forward return self.forward_test(img_r, img_i, img_meta, source_img_r, source_img_i, **kwargs) File "/home/ywc/temp/DetFusion/mmdet/models/detectors/base.py", line 107, in forward_test return self.simple_test(imgs_r[0], imgs_i[0], img_metas[0], source_img_r[0], source_img_i[0], **kwargs) File "/home/ywc/temp/DetFusion/mmdet/models/detectors/detfusion.py", line 556, in simple_test im_fusion = self.fusion_head(source_img_r/255.0, source_img_i/255.0, att_rgb, att_tir) File "/home/ywc/miniconda3/envs/detfusion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/ywc/temp/DetFusion/mmdet/models/bbox_heads/fusion_head_bbox.py", line 72, in forward enc_fusion = enc_fusion + enc_fusion * up_att_w RuntimeError: The size of tensor a (640) must match the size of tensor b (608) at non-singleton dimension 3



> File "/home/ywc/temp/DetFusion/test.py", line 31, in save_fusion_result('./configs/DetFusion.py', './work_dirs/DetFusion/model.pth', img_dir='./evaluateimgs/') File "/home/ywc/temp/DetFusion/test.py", line 26, in save_fusion_result image_fusion = inference_detector(model, img_path_r, img_path_i) File "/home/ywc/temp/DetFusion/mmdet/apis/inference.py", line 60, in inference_detector return _inference_single(model, imgs_r, imgs_i, img_transform, device) File "/home/ywc/temp/DetFusion/mmdet/apis/inference.py", line 120, in _inference_single result_r, result_i, image_fusion = model(return_loss=False, rescale=True, **data) File "/home/ywc/miniconda3/envs/detfusion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/ywc/temp/DetFusion/mmdet/models/detectors/base.py", line 116, in forward return self.forward_test(img_r, img_i, img_meta, source_img_r, source_img_i, **kwargs) File "/home/ywc/temp/DetFusion/mmdet/models/detectors/base.py", line 107, in forward_test return self.simple_test(imgs_r[0], imgs_i[0], img_metas[0], source_img_r[0], source_img_i[0], **kwargs) File "/home/ywc/temp/DetFusion/mmdet/models/detectors/detfusion.py", line 556, in simple_test im_fusion = self.fusion_head(source_img_r/255.0, source_img_i/255.0, att_rgb, att_tir) File "/home/ywc/miniconda3/envs/detfusion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/ywc/temp/DetFusion/mmdet/models/bbox_heads/fusion_head_bbox.py", line 72, in forward enc_fusion = enc_fusion + enc_fusion * up_att_w RuntimeError: The size of tensor a (640) must match the size of tensor b (608) at non-singleton dimension 3

**Comment by 2252033991** [comment]
Pls how to solve this problem, I am also experiencing such a problem
